// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA92odyF6cHYokNYouJkiUfzdLqwdOrYpQ',
    appId: '1:564751904449:web:ef2b359f01229340962e40',
    messagingSenderId: '564751904449',
    projectId: 'proton-911e9',
    authDomain: 'proton-911e9.firebaseapp.com',
    storageBucket: 'proton-911e9.appspot.com',
    measurementId: 'G-ZY4Z8R04JL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBurzUyNpf8h_KoEL58pkrNlHW88N_nrGg',
    appId: '1:564751904449:android:3e2260bc21326013962e40',
    messagingSenderId: '564751904449',
    projectId: 'proton-911e9',
    storageBucket: 'proton-911e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWJAnRLmntMQvMD2bl0ui3WHXvtJuNZGE',
    appId: '1:564751904449:ios:cf34482e2f01d15e962e40',
    messagingSenderId: '564751904449',
    projectId: 'proton-911e9',
    storageBucket: 'proton-911e9.appspot.com',
    iosClientId:
        '564751904449-98e0ro6qnimgcbrs8skhhm3g49aqng9f.apps.googleusercontent.com',
    iosBundleId: 'com.example.proton',
  );
}
